"""生成聚合视图：INDEX.md / graph.json / registry.json，并回填 consumers。

这是 token 效率的第一层：Claude 默认只读 INDEX.md。
"""
from __future__ import annotations

import json

from .config import Paths, paths
from .contract import Contract, load_all
from . import graph as G

_INDEX_HEADER = """<!-- GENERATED by `dw index` — 请勿手工编辑 -->
# 数据集索引

共 {n} 个 dataset。**先读本文件，再按需 `dw show <name>` 展开单个合约。**
命令备忘：`dw ls` `dw search <kw>` `dw show <ds>` `dw deps <ds> --down` `dw impact <ds>`

| dataset | domain | grain | 列数 | status | upstream | purpose |
|---|---|---|---|---|---|---|
"""


def build_registry(contracts: dict[str, Contract], g: dict) -> dict:
    """对外/对内调用注册表：消费方只读这个文件就知道有什么、怎么调。"""
    entries = {}
    for name, c in contracts.items():
        entries[name] = {
            "name": name,
            "version": c.version,
            "status": c.status,
            "domain": c.domain,
            "family": c.family or (name.split("__")[0] if "__" in name else ""),
            "tags": c.tags,
            "purpose": c.purpose,
            "grain": c.grain,
            "partitions": c.partitions,
            "columns": [
                {"name": col.name, "type": col.type, "nullable": col.nullable, "desc": col.desc}
                for col in c.columns
            ],
            "upstream": [{"kind": u.kind, "ref": u.ref} for u in c.upstream],
            "consumers": c.consumers,
            "sla": c.sla.model_dump(),
            "access": {
                "polars": f'dw.load("{name}")',
                "arrow": f'dw.arrow("{name}")',
                "sql": f'dw.sql("select * from {name}")',
            },
        }
    return {"version": 1, "datasets": entries}


def reindex(p: Paths | None = None, scan: bool = True) -> dict:
    """重建全部生成物。返回统计信息。"""
    p = p or paths()
    contracts = load_all(p)
    g = G.build(p, scan=scan)

    # consumers 是**派生字段**：只算进内存 / graph / registry，绝不回写 contract.yaml
    # （回写会抹掉人写的注释与排版，而合约是人读人写的真源）
    for name, c in contracts.items():
        downs = {e["to"] for e in g["edges"] if e["kind"] == "dataset" and e["from"] == name}
        downs |= {r["in_dataset"] for r in g["refs"].get(name, []) if r["in_dataset"]}
        downs.discard(name)
        c.consumers = sorted(downs)
        g["nodes"].setdefault(name, {})["consumers"] = c.consumers

    G.save(g, p)

    p.contracts_dir.mkdir(parents=True, exist_ok=True)
    rows = "\n".join(c.summary_line() for _, c in sorted(contracts.items()))
    p.index_md.write_text(
        _INDEX_HEADER.format(n=len(contracts)) + rows + "\n", encoding="utf-8"
    )
    reg = build_registry(contracts, g)
    p.registry_json.write_text(
        json.dumps(reg, ensure_ascii=False, indent=1, sort_keys=True), encoding="utf-8"
    )
    dangling = sorted(
        {e["from"] for e in g["edges"] if e["kind"] == "dataset"} - set(contracts)
    )
    return {
        "datasets": len(contracts),
        "edges": len(g["edges"]),
        "refs": sum(len(v) for v in g["refs"].values()),
        "dangling": dangling,
    }


def load_registry(p: Paths | None = None) -> dict:
    p = p or paths()
    if not p.registry_json.is_file():
        return {"version": 1, "datasets": {}}
    return json.loads(p.registry_json.read_text(encoding="utf-8"))
